global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mhmanus-monitor'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/alerts.rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API monitoring
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'

  # Frontend monitoring (if metrics endpoint is exposed)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:4200']
    metrics_path: '/metrics'

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Loki monitoring
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3001']