apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "5s"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus-uid
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki-uid
        mapTagNamesEnabled: false
        mappedTags:
          - key: service.name
            value: service
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: prometheus-uid
      search:
        hide: false
      nodeGraph:
        enabled: true